version: '3'
services:

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: mysql_treasy
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=treasy
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456 
    volumes:
      - ./mysql/dbdata:/var/lib/mysql/